# Generated by Django 2.1.7 on 2019-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_NO', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=50)),
                ('aadharNo', models.CharField(max_length=50)),
                ('aadhar_Image', models.ImageField(upload_to='document/images')),
                ('panCard_Image', models.ImageField(upload_to='document/images')),
                ('profile_pic', models.ImageField(upload_to='profile_pic/images')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('is_active', models.BooleanField(null=True)),
                ('is_deleted', models.BooleanField(null=True)),
            ],
        ),
    ]
